### ISSUE TITLE
Релиз

### ISSUE THREAD

**Issue by RykovDC** [samoswall/hacs-polaris#3]
Только что пришло обновление приложения Polaris на iOS с описанием "добавлена интеграция с Home Assistant". Когда опубликуете релиз? 
![IMAGE 2024-03-04 17:07:11](https://github.com/samoswall/hacs-polaris/assets/139807719/45487585-e22a-4aeb-a353-adf6bab49856)

**Comment by evd1ser** [comment]
Они для избранных запустили что то свое походу… но лучше разнообразие а не ждать от официалов по пол года исправление багов
![IMG_0652](https://github.com/samoswall/hacs-polaris/assets/15332093/741bd8ae-0d1e-43a6-a768-c7c50befbfd4)

**Comment by RykovDC** [comment]
> Они для избранных запустили что то свое походу… но лучше разнообразие а не ждать от официалов по пол года исправление багов
> 
> ![IMG_0652](https://github.com/samoswall/hacs-polaris/assets/15332093/741bd8ae-0d1e-43a6-a768-c7c50befbfd4)
> 
> 

Да, они мне тоже самое сейчас ответили

**Comment by deker1176** [comment]
Есть информация когда опубликуют ? Или можно без нее установить ?

**Comment by RykovDC** [comment]
> Есть информация когда опубликуют ? Или можно без нее установить ? 

А как вы её установите?

**Comment by samoswall** [comment]
Polaris заявил о поддержке Home Assistant.
Да, действительно новые модели разрабатываются с поддержкой, и в приложении у этих девайсов есть настройка для подключению к Вашему MQTT брокеру. Пока на этом всё. Функция находится на стадии тестирования и доступна бета тестерам. Discovery для HA пока отсутствует, может позже добавят, но ни где об этом не заявляли.
Для старых девайсов, требуется обновление прошивки - прошивки так же сначала пройдут через бета тестеров.
Про интеграцию Polaris пока ничего не говорит, и ни кто про неё ничего не слышал.
Я решил ее писать по собственной инициативе и по тому, что мне это интересно.
До конца месяца сделаю первый релиз!

**Comment by samoswall** [comment]
Проект закрыт

**Comment by deker1176** [comment]
> > Есть информация когда опубликуют ? Или можно без нее установить ? 
> 
> А как вы её установите? 

Не ну может как то можно установить минуя hacs?

**Comment by RykovDC** [comment]
Обидно (( ждали вас, а теперь Поларис 3 года ждать

**Comment by deker1176** [comment]
Да я бы тоже @samoswall воспользовался бы данной разработкой... Поларис может сказать и не сделать ещё несколько лет...

**Comment by RykovDC** [comment]
Может все таки получить вернуть интеграцию в разработку?

**Comment by samoswall** [comment]
Первый этап - поддержка mqtt уже есть, если Вы в комьюните тестеров, то значит получили прошивку, или запросите прошивку через поддержку. По нашей с Вами просьбе на 4pda, количество тестеров увеличили.
Для всех чайников прошивки готовы, для других девайсов - спрашивать в поддержке.
При наличии поддержки mqtt - интеграция не нужна! Максимум скрипт, который задисковерит девайс.

**Comment by deker1176** [comment]
К сожалению не в команде техподдержки...

**Comment by deker1176** [comment]
А у вас как раз была готова разработка для увлажнителя...

**Comment by samoswall** [comment]
Я поднял сущности :
sensor -  в нем автопоиск новых девайсов, при обнаружении нового, переконфигурация а после перезагрузка интеграции
switch
water_heater
light - разобрался, но не понял кому его добавлять (какие устройства поддерживают RGB цвет, а каким просто swith делать)
humidifier - разобрался, но не сделал (так же как и water_heater - теперь легко добавить).
Последние дни пытался разобраться с добавлением иконок в режимы water_heater или humidifier.
В целом принцип разработки интеграции мне теперь понятен. Даже с учетом изменившейся структуры топика Polaris, после обновления, немного упрощается код.
Сейчас наступил момент, когда есть старый вариант девайсов - c которым нужно работать по UDP или поднимать контейнер со старой версией MQTT и перенаправлением трафика, и новый вариант - в котором можно скриптом сделать discovery, а с учетом реализации discovery в прошивке и он не нужен. (думаю многим понятно, что скрипт делает практически то, что мы прописываем в configuration.yaml. Большой скрипт, просто будет содержать все девайсы и добавлять только тот девайс, который необходим)
В политике Home Assistant интеграция, которая читает mqtt топик и создает девайс уже есть - называется MQTT, поэтому новая интеграция для новых девайсов Polaris добавлена в Home Assistant не будет.
Для старых девайсов Polaris - пока интеграция будет тестироватся, пока будут добавляться протестированные устройства - старых девайсов не останется, по крайней мере чайников и увлажнителей, которых основная масса в % соотношении.
**Не вижу смысла заниматься интеграцией, которая через год станет не актуальной.**

P.S. Если есть желание пользоваться интеграцией (при условии, что девайс уже в вашем mqtt брокере, а значит вы его уже добавили через yaml и нового вы ни чего не увидете, т.к. UDP я еще не подключал) то могу поделиться наработками и пояснить если надо.

**Comment by RykovDC** [comment]
> Первый этап - поддержка mqtt уже есть, если Вы в комьюните тестеров, то значит получили прошивку, или запросите прошивку через поддержку. По нашей с Вами просьбе на 4pda, количество тестеров увеличили. Для всех чайников прошивки готовы, для других девайсов - спрашивать в поддержке. При наличии поддержки mqtt - интеграция не нужна! Максимум скрипт, который задисковерит девайс.

Запросил прошивку, осталось лишь понять как её накатить.

**Comment by deker1176** [comment]
> > Первый этап - поддержка mqtt уже есть, если Вы в комьюните тестеров, то значит получили прошивку, или запросите прошивку через поддержку. По нашей с Вами просьбе на 4pda, количество тестеров увеличили. Для всех чайников прошивки готовы, для других девайсов - спрашивать в поддержке. При наличии поддержки mqtt - интеграция не нужна! Максимум скрипт, который задисковерит девайс.
> 
> Запросил прошивку, осталось лишь понять как её накатить. 

А где запросил? Я тоже в приложении написал в техподдержку и тишина..

**Comment by RykovDC** [comment]
![image](https://github.com/samoswall/hacs-polaris/assets/139807719/7d2f8d98-b3ad-4098-961b-0666ac9b01fc)

**Comment by RykovDC** [comment]
Нашел как накатить. Нужно зажать на несколько секунд строку "версия прошивки" и выбрать файл

**Comment by RykovDC** [comment]
Вот только что сюда писать пока не пойму 
![image](https://github.com/samoswall/hacs-polaris/assets/139807719/8c806745-2ad2-4575-82c0-43fac4ebaa70)

**Comment by RykovDC** [comment]
Устройство не появляется в MQTT

**Comment by samoswall** [comment]
> Устройство не появляется в MQTT

Думаю по SSL без пароля не получится.

**Comment by RykovDC** [comment]
> > Устройство не появляется в MQTT
> 
> Думаю по SSL без пароля не получится.

Да нет, адрес сервера и порт я прописал, пользователя и пароль тоже но без ssl. В MQTT Explorer чайник отобразился, но я не вижу его в брокере.

**Comment by samoswall** [comment]
> В MQTT Explorer чайник отобразился, но я не вижу его в брокере.

MQTT Explorer отображает состояние брокера! Поэтому в брокере он точно есть!
Если имелось ввиду - но я не вижу его в **интеграции MQTT**, то
> Второй этап - MQTT Discovery для Home Assistant.
еще не начался! Поэтому добавляем через configuration.yaml

**Comment by RykovDC** [comment]
> > В MQTT Explorer чайник отобразился, но я не вижу его в брокере.
> 
> MQTT Explorer отображает состояние брокера! Поэтому в брокере он точно есть! Если имелось ввиду - но я не вижу его в **интеграции MQTT**, то
> 
> > Второй этап - MQTT Discovery для Home Assistant.
> 
> еще не начался! Поэтому добавляем через configuration.yaml

А как?

**Comment by evd1ser** [comment]
@RykovDC https://4pda.to/forum/index.php?showtopic=1051392&st=160#entry123725639 - сам минут 10 назад пользовался этой ссылкой
<img width="586" alt="Снимок экрана 2024-03-25 в 15 26 24" src="https://github.com/samoswall/hacs-polaris/assets/15332093/01856d3e-b7e1-47cb-b466-03790cb1c468">

**Comment by samoswall** [comment]
> А как?

[Начните с этого поста на4pda](https://4pda.to/forum/index.php?showtopic=1051392&view=findpost&p=123725639)

**Comment by RykovDC** [comment]
Все получилось! ![image](https://github.com/samoswall/hacs-polaris/assets/139807719/aaab4602-6e4f-450b-a351-b2c78a91cce9)

**Comment by deker1176** [comment]
Хорошо вам с чайником а у меня увлажнитель не выпустили ещё прошивку и хз когда будет...
